# Generated by Django 4.1 on 2022-09-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
